[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Mark test as smoke test
    regression: Mark test as regression test
    sanity: Mark test as sanity test
